name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore dependencies
        run: dotnet restore; nuget restore $SOLUTION
      - name: Build
        run: dotnet build --configuration Release --no-restore --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Pack
        run: dotnet pack --configuration Release
      - name: Publish
        run: dotnet nuget push *.nupkg --no-symbols --skip-duplicate
        env:
         NUGET_AUTH_TOKEN: ${{ github.token }}
